filesets:
    includes:
        - README.md
        - ngrok-config
    excludes:
        - \.git
        - .gobuild.yml
        - ngrok.go
settings:
        build: |
            if test "$GOOS" = "windows" -a "$GOARCH" = "386"
            then
                go install -v -ldflags "-s -w" -tags 'release'
            else
                go install -v -ldflags "-s -w" -tags 'release'
            fi