filesets:
    includes:
        - README.md
        - cert.pem
        - key.pem
    excludes:
        - \.git
        - .gobuild.yml
settings:
        build: |
            if test "$GOOS" = "windows" -a "$GOARCH" = "386"
            then
                go install -v
            else
                go install -v
            fi